import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        <header className="border-b">
          <div className="mx-auto max-w-5xl px-4 py-3">
            <h1 className="text-lg font-medium">SymbolSite</h1>
          </div>
        </header>

        <main className="mx-auto max-w-5xl px-4 py-6">{children}</main>

        <footer className="border-t">
          <div className="mx-auto max-w-5xl px-4 py-3 text-sm text-gray-500">
            © {new Date().getFullYear()} SymbolSite
          </div>
        </footer>
      </body>
    </html>
  );
}
